apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: server
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: us.gcr.io/eiad-219804/webserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
